# Generated by Django 4.1.1 on 2022-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=150)),
                ("location_link", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=150, null=True)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
