# Generated by Django 4.1.1 on 2022-10-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0002_contact_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sections",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="center.courses",
            ),
        ),
        migrations.AlterField(
            model_name="sections",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Course"),
        ),
        migrations.AlterField(
            model_name="sections",
            name="name",
            field=models.CharField(default="name", max_length=50),
            preserve_default=False,
        ),
    ]
